[package]
name = "jbig2-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.jbig2-rs]
path = ".."

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_reader"
path = "fuzz_targets/fuzz_reader.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_arithmetic"
path = "fuzz_targets/fuzz_arithmetic.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_bitmap"
path = "fuzz_targets/fuzz_bitmap.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_mmr"
path = "fuzz_targets/fuzz_mmr.rs"
test = false
doc = false
bench = false
